FROM centos
RUN yum install -y java
VOLUME /tmp
EXPOSE 8010
ADD /target/API_Services_VNF_LCM-1.0.0.jar dockerdemo.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/dockerdemo.jar"]